targets:
  $default:
    sources:
      exclude:
        - bin/*.dart
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
          generic_argument_factories: false
