name: bloc_architecture
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: 3.24.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  google_fonts: ^6.2.1
  skeletonizer: ^1.4.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  shared_preferences: ^2.3.2
  auto_route: ^9.2.2
  device_info_plus: ^10.1.2
  visibility_detector: ^0.4.0+2
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  velocity_x: ^4.2.1
  provider: ^6.1.2
  collection: ^1.18.0
  synchronized: ^3.1.0+1
  flutter_secure_storage: ^9.2.2
  flutter_hooks: ^0.20.5
  uuid: ^4.5.1
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.1
  retrofit: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  retrofit_generator: ">=8.0.0 <10.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_gen:
  output: lib/core/collections
  assets:
    outputs:
      class_name: Assets
      style: camel-case
  integrations:
    flutter_svg: true
  fonts:
    outputs:
      class_name: MyFontFamily
    enabled: true
  exclude: null
